-- for checking the time taken for the query
SET TIMING ON;

-- for describing data present in HR_Department Table
DESC HR_DEPARTMENT

-- fetching all records in HR_Department 
SELECT * FROM HR_DEPARTMENT

-- QUERY 1 : TO FIND THE EMPLOYEE COUNT FOR EACH AGENCY

SELECT AGENCY, COUNT(*) NO_OF_EMPLOYEES
FROM HR_DEPARTMENT
GROUP BY AGENCY
ORDER BY AGENCY;

-- QUERY 2 : TO LIST THE EMPLOYEES WHO ARE ALL CONTRACTUAL WORKER

CREATE INDEX HR_POSITON ON HR_DEPARTMENT("Position Title");

SELECT "Employee Name" AS "CONTRACTUAL WORKER" FROM HR_DEPARTMENT
WHERE "Position Title" = 'CONTRACTUAL WORKER' ORDER BY  1;

--QUERY 3 : TO LIST THE EMPLOYEE NAME WORK UNDER AGENCY ABE LINCON PRES LIBRARY  MUS2

CREATE INDEX HR_AGENCY on HR_DEPARTMENT (AGENCY);

SELECT "Employee Name" FROM HR_DEPARTMENT
WHERE AGENCY = 'ABE LINCOLN PRES LIBRARY MUS2';

-- QUERY 4 : TO FIND THE EMPLOYEES COUNT IN EACH POSITION

SELECT "Position Title",COUNT(*) NO_OF_EMPLOYEES FROM HR_DEPARTMENT 
GROUP BY "Position Title" order by 2;

--QUERY 5 : TO COUNT THE NUMBER OF EMPLOYEES WHOSE PERIOD PAY RATE IS LESS THAN 50000

SELECT COUNT(*) NO_OF_EMPLOYEES FROM HR_DEPARTMENT
WHERE "Period Pay Rate" <50000;